### ISSUE TITLE
Incompatible with Term::ShellUI

### ISSUE THREAD

**Issue by ygale** [rocky/p5-Term-ReadLine-Perl5#8]
Starting with version 1.37, `Term::ReadLine::Perl5` became incompatible with `Term::ShellUI`.

I encountered this while trying to install [kpcli](https://sourceforge.net/projects/kpcli/). Up until version 1.36, everything works fine. Starting with 1.37, when I try to start kpcli, I get this error:

    Prototype mismatch: sub Term::ReadLine::Perl5::readline::add_line_to_history ($$) vs none at .../bin/kpcli-2.8.pl line 4639.

The kpcli shell does start after the error, but I'm not sure if it's fully functional. Starting with version 1.39, kpcli does not start at all, and the full error message becomes:

    Prototype mismatch: sub Term::ReadLine::Perl5::readline::add_line_to_history ($$) vs none at .../bin/kpcli-2.8.pl line 4639.
    Not an ARRAY reference at /System/Library/Perl/5.18/Term/ReadLine.pm line 307.

I am not a Perl programmer; just a user. Lester Hightower of the kpcli project requested in the [kpcli issue](https://sourceforge.net/p/kpcli/bugs/18/) that I report it here.

**Comment by rocky** [comment]
I just put out another release, 1.42 which I think should address this. Try that out. (Right now I don't see that version on CPAN serach or meta).  If that works then close this.

**Comment by hightowe** [comment]
Hi, I'm the author of kpcli. I don't think that 1.42 fixed it:

hightowe@zion:~$ pmvers Term::ReadLine::Perl5
1.42
hightowe@zion:~$ ~/bin/kpcli.d/kpcli-DEVELOPMENT.pl 
Not an ARRAY reference at /usr/share/perl/5.18/Term/ReadLine.pm line 307.

Here is a command-line test case that shows it's not kpcli code:

hightowe@zion:~$ perl -MTerm::ShellUI -MTerm::ReadLine::Gnu -e '$term=Term::ReadLine::Gnu->new("test"); my $shell = new Term::ShellUI(app => "test", term => $term); print "works\n";'
Use of inherited AUTOLOAD for non-method Term::ReadLine::Gnu::ornaments() is deprecated at /usr/lib/perl5/Term/ReadLine/Gnu.pm line 250.
works

hightowe@zion:~$ perl -MTerm::ShellUI -MTerm::ReadLine::Perl -e '$term=Term::ReadLine::Perl->new("test"); my $shell = new Term::ShellUI(app => "test", term => $term); print "works\n";'
works

hightowe@zion:~$ perl -MTerm::ShellUI -MTerm::ReadLine::Perl5 -e '$term=Term::ReadLine::Perl5->new("test"); my $shell = new Term::ShellUI(app => "test", term => $term); print "works\n";'
Not an ARRAY reference at /usr/share/perl/5.18/Term/ReadLine.pm line 307.

Hope this is helpful.

--
Lester

**Comment by rocky** [comment]
Just tracked this down. Sigh. 

Between version 1.38 and 1.39, Term::ReadLine::Perl5 moved to a more OO version of Readline.

Perl has this (mis)feature where you can bless any type, so people do. And in the case of Term::Readline what's blessed is an array where 0 is input and 1 is output. This makes it difficult/ugly/unconventional to try to turn ReadLine into a decent OO interface.  So I'll work up a patch to Term::ShellUI so that it doesn't assume Term::ReadLine is an array.

**Comment by rocky** [comment]
I think with version 1.43 which is on PAUSE but not seen on CPAN yet, I think I finally have this fixed on my side. When that comes though and if it works, close the ticket.

Thanks, Lester for all of the help and support.

**Comment by ygale** [comment]
Yes it works for me. Thanks!
